### PR TITLE
Fixing feature/WYSIWYD

### PR DESCRIPTION
**Pull request by pattacini**
- Lots of warnings fixed, some of which are quite significant.
- Made `opencv-3.x.y` friendly.

The idea is to first merge these fixes into `feature/WYSIWYD` and then proceed with merging `feature/WYSIWYD` into `master`.

@alecive and @matejhof please have a look at this.
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/robotology/peripersonal-space/pull/21%23issuecomment-212423036%22%2C%20%22https%3A//github.com/robotology/peripersonal-space/pull/21%23issuecomment-212423262%22%2C%20%22https%3A//github.com/robotology/peripersonal-space/pull/21%23issuecomment-212427223%22%2C%20%22https%3A//github.com/robotology/peripersonal-space/pull/21%23issuecomment-212427361%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/robotology/peripersonal-space/pull/21%23issuecomment-212423036%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Wow%20all%20of%20these%20were%20warning%20on%20windows%3F%20You%20should%20have%20done%20the%20pull%20request%20before%21%5Cr%5CnA%20question%3A%20you%20replaced%20%5Cr%5Cn%60%60%60%5Cr%5Cn%23include%20%3Ccv.h%3E%5Cr%5Cn%23include%20%3Chighgui.h%3E%5Cr%5Cn%60%60%60%5Cr%5Cnwith%20%60%23include%20%3Copencv2/opencv.hpp%3E%60.%5Cr%5CnWhy%20didn%27t%20you%20replace%20them%20with%3A%5Cr%5Cn%60%60%60%5Cr%5Cn%23include%20%3Copencv2/core/core.hpp%3E%5Cr%5Cn%23include%20%3Copencv2/highgui/highgui.hpp%3E%5Cr%5Cn%60%60%60%5Cr%5Cn%3F%5Cr%5Cn%5Cr%5CnA%20part%20from%20that%2C%20PR%20approved.%22%2C%20%22created_at%22%3A%20%222016-04-20T13%3A24%3A54Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4378663%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/alecive%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222016-04-20T13%3A25%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4378663%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/alecive%22%7D%7D%2C%20%7B%22body%22%3A%20%22The%20%60highgui.hpp%60%20header%20file%20is%20simply%20not%20necessary%20for%20the%20compilation%20%3Awink%3A.%22%2C%20%22created_at%22%3A%20%222016-04-20T13%3A39%3A34Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%2C%20%7B%22body%22%3A%20%22%3A%2B1%3A%22%2C%20%22created_at%22%3A%20%222016-04-20T13%3A40%3A04Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/3738070%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/pattacini%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22approved%22%3A%20%7B%22https%3A//github.com/alecive%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/4378663%3Fv%3D3%22%7D%7D%7D'></a>
<a href='https://www.codereviewhub.com/'></a>

<a href='https://github.com/alecive'></a>

- [x] <a href='#crh-comment-General Comment'></a> &nbsp;<b><a href='https://github.com/robotology/peripersonal-space/pull/21#issuecomment-212423036'>General Comment</a></b>
- <a href='https://github.com/alecive'></a> Wow all of these were warning on windows? You should have done the pull request before!
A question: you replaced
```
#include <cv.h>
#include <highgui.h>
```
with `#include <opencv2/opencv.hpp>`.
Why didn't you replace them with:
```
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
```
?
A part from that, PR approved.
- <a href='https://github.com/alecive'></a> :shipit:
- <a href='https://github.com/pattacini'></a> The `highgui.hpp` header file is simply not necessary for the compilation :wink:.

<a href='https://www.codereviewhub.com/robotology/peripersonal-space/pull/21?mark_as_completed=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/peripersonal-space/pull/21?approve=1'></a>&nbsp;<a href='https://www.codereviewhub.com/robotology/peripersonal-space/pull/21?approve=0'></a>&nbsp;<a href='https://github.com/robotology/peripersonal-space/pull/21'></a>
<a href='#crh-end'></a>

### CODE REVIEW

**Comment by pattacini** [comment]
This pull request is now managed with CodeReviewHub. <a href='https://github.com/robotology/peripersonal-space/pull/21'>Refresh</a>.<a href='#crh-update-none'></a>

**Comment by alecive** [comment]
Wow all of these were warning on windows? You should have done the pull request before!
A question: you replaced 
```
#include <cv.h>
#include <highgui.h>
```
with `#include <opencv2/opencv.hpp>`.
Why didn't you replace them with:
```
#include <opencv2/core/core.hpp>
#include <opencv2/highgui/highgui.hpp>
```
?

A part from that, PR approved.

**Comment by alecive** [comment]
:shipit:

**Comment by pattacini** [comment]
The `highgui.hpp` header file is simply not necessary for the compilation :wink:.

**Comment by pattacini** [comment]
:+1:

**Pull request merged**
